language: java
sudo: false
jdk: oraclejdk8

#env:
#  global:
#    - PATH=$HOME/.local/bin:$PATH

stages:
  - compile
  - test
#  - deploy
#  - code_coverage

before_install:
  - chmod +x mvnw
  
install: true

jobs:
  include:
    - stage: compile
      name: "Compile project"
      script: ./mvnw clean install -DskipTests

    - stage: test
      name: "Codecov test report"
      script: "mvn cobertura:cobertura"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
