language: java
sudo: false
jdk: oraclejdk8

stages:
  - compile
  - test
#  - deploy
  - code_coverage

before_install:
  - chmod +x mvnw
  
install: true

jobs:
  include:
    - stage: compile
      name: "create mvn env"
      script: ./mvnw clean install -DskipTests

    - stage: test
      name: "unit tests"
      script: ./mvnw surefire:test

    - stage: code_coverage
      name: "Codecov report"
      script: "mvn cobertura:cobertura"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
