language: java
sudo: true
jdk: oraclejdk8

before_install:
  - chmod +x mvnw
install: true
script:
  - ./mvnw clean install
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

